FROM python:3.7-slim-stretch

WORKDIR /var/task
#FROM r-base:latest

#RUN pip install --upgrade pip virtualenv pyflakes
#RUN mkdir -p ./snowalert
#RUN python3 -m venv ./snowalert/venv
#ENV PATH="./snowalert/venv/bin:${PATH}"

COPY ./src ./snowalert/src

RUN pip3 install wheel ./snowalert/src/

RUN apt-get update \
&& apt-get install -y r-base vim

RUN R -e "install.packages('dplyr', repos = 'https://cloud.r-project.org')"

CMD ./snowalert/src/sars/run.sh
