#!/bin/bash

if [[ -d "/var/task/snowalert/venv/bin" && -d "/var/task/snowalert/src" ]]; then
  echo "running in docker container-like environment"

  if [[ "$1" == "webui" ]]; then

    cd /var/task/snowalert/src/webui/backend
    python webui/app.py

  else

    cd /var/task/snowalert/src/runners/
    python run.py $@

  fi

elif [[ -d "$HOME/.snowsql" && -d "$HOME/.aws" ]]; then
  echo "running in client development-like environment"

  if [[ ! -f "$1" ]]; then
    >&2 echo "usage: ./run snowalert-{env}.envs {command}"
    >&2 echo "if you don't have an env file, run ./install first"
    exit 1
  fi

  docker run -it --env-file "$1" snowsec/snowalert ./run $2

else

  echo "please run in docker or make sure you have aws credentials in ~/.aws and snowflake credentials in ~/.snowsql"

fi
