#!/bin/bash

if [[ -d "/var/task/snowalert/venv/bin" && -d "/var/task/snowalert/src" ]]; then
  echo "running in docker container-like environment"

  cd /var/task/snowalert/src/runners/

  if [ -z "$1" ]; then
    ./alert_queries_runner.py
    ./alert_suppressions_runner.py
    ./violation_queries_runner.py
    ./violation_suppressions_runner.py
    ./alert_handler.py

  elif [ "$1" == "alerts" ]; then
    ./alert_queries_runner.py
    ./alert_suppressions_runner.py

  elif [ "$1" == "violations" ]; then
    ./violation_queries_runner.py
    ./violation_suppressions_runner.py

  elif [ "$1" == "alert_queries" ]; then
    ./alert_queries_runner.py

  elif [ "$1" == "alert_suppressions" ]; then
    ./alert_suppressions_runner.py

  elif [ "$1" == "violation_queries" ]; then
    ./violation_queries_runner.py

  elif [ "$1" == "violation_suppressions" ]; then
    ./violation_suppressions_runner.py

  elif [ "$1" == "alert_handler" ]; then
    ./alert_handler.py

  fi

elif [[ -d "$HOME/.snowsql" && -d "$HOME/.aws" ]]; then
  echo "running in client development-like environment"

  if [[ ! -f "$1" ]]; then
    >&2 echo "usage: ./run snowalert-{env}.envs"
    >&2 echo "if you don't have an env file, run ./install first"
    exit 1
  fi

  docker run -it --env-file "$1" snowsec/snowalert ./run

else

  echo "please run in docker or make sure you have aws credentials in ~/.aws and snowflake credentials in ~/.snowsql"

fi
