#!/usr/bin/env bash
#
# Run whitesource for components which need versioning

set -x
# Never ever fail for whitesource problems
set +e

# SCAN_DIRECTORIES is a comma-separated list (as a string) of file paths which contain all source code and build artifacts for this project
SCAN_DIRECTORIES=`pwd`

# PRODUCT_NAME is your team's name or overarching project name
PRODUCT_NAME="SNOWALERT"

# PROJECT_NAME is your project's name or repo name if your project spans multiple repositories
PROJECT_NAME="SNOWALERT"

DATE=$(date +'%m-%d-%Y')

# Download the latest whitesource unified agent to do the scanning if there is no existing one
if [ ! -f "wss-unified-agent.jar" ]; then
   curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar
fi

# whitesource will scan the folder and detect the corresponding configuration
# configuration file wss-generated-file.config will be generated under ${SCAN_DIRECTORIES}
# java -jar wss-unified-agent.jar -detect -d ${SCAN_DIRECTORIES}
# SCAN_CONFIG="${SCAN_DIRECTORIES}/wss-generated-file.config"

# SCAN_CONFIG is the path to your whitesource configuration file
SCAN_CONFIG="${PWD}/wss-agent.config"

java -jar wss-unified-agent.jar -apiKey ${WHITESOURCE_API_KEY} \
   -c ${SCAN_CONFIG} \
   -project ${PROJECT_NAME} \
   -product ${PRODUCT_NAME} \
   -projectVersion ${DATE} \
   -d ${SCAN_DIRECTORIES} \
   -wss.url https://saas.whitesourcesoftware.com/agent

exit 0
